# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    stdlib: "puppetlabs/stdlib"
    cron: "puppet/cron"
    nginx: "puppet/nginx"
    apt: "puppetlabs/apt"
    letsencrypt: "puppet/letsencrypt"
    logrotate: "puppet/logrotate"
    firewall: "puppetlabs/firewall"
    firewall_multi: "alexharvey/firewall_multi"
    systemd: "puppet/systemd"
    concat: "puppetlabs/concat"
    inifile: "puppetlabs/inifile"
    epel: "puppet/epel"

