#useful aliases for OntoPortal
alias suo="sudo su - ontoportal"
alias gtc="pushd /opt/ontoportal/ncbo_cron"
alias gta="pushd /opt/ontoportal/ontologies_api/current"
alias gtu="pushd /opt/ontoportal/bioportal_web_ui/current"
alias gtv="pushd /opt/ontoportal/virtual_appliance"
alias gtp="pushd /etc/puppetlabs/code/environments/production"
alias tla="tail -fn 100 /opt/ontoportal/ontologies_api/current/log/appliance.log"
alias tlu="tail -fn 100 /opt/ontoportal/bioportal_web_ui/current/log/appliance.log"
alias tlc="tail -fn 100 /opt/ontoportal/ncbo_cron/logs/scheduler.log"
alias oprestart="sudo /usr/local/bin/oprestart"
alias opstart="sudo /usr/local/bin/opstart"
alias opstop="sudo /usr/local/bin/opstop"
alias runpuppet="/opt/ontoportal/virtual_appliance/utils/infra/run_masterless_puppet.sh"
alias runpuppetnoop="/opt/ontoportal/virtual_appliance/utils/infra/run_masterless_puppet.sh noop"
